"""<br>
@Author:Vijay Kumar M N<br>
@Date: 2024-08-20<br>
@Last Modified by: Vijay Kumar M N<br>
@Last Modified: 2024-08-20<br>
@Title : python program for Numpy  build-in functions.<br>
"""

In [1]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional<br>
NumPy array.<br>

In [2]:
def main():
    """
    Description:
        This is function is used to convert list into one-dimensional Numpy array
    Parameters:
        None
    returns:
        None"""
    original_list=[12.23, 13.32,100,36.32]
    result=np.array(original_list)
    print(result)
if __name__=="__main__":
    main()



[ 12.23  13.32 100.    36.32]


2.Create a 3x3 matrix with values ranging from 2 to 10.<br>


In [3]:
def matrix(array):
    """
    Description:
        This Function is used to convert the 3x3 matrix
    
    Parameters:
        array : ndarray which having the numbers from 2 to 10
    
    returns:
        new_array: ndarray which will return the 3x3 matrix
    """
    new_array=array.reshape(3,3)
    return new_array
def main():
    #creating a 1d array by using the arange function.
    numbers=np.arange(2,11)
    result=matrix(numbers)
    print(result)
if __name__=="__main__":
    main()


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.<br>


In [4]:
def replace_vector(array):
    
    """
    Description:
        This function will replace the sixth index with 11
    
    parameters:
        array: ndarray which consists of elements of zeros
    
    return:
        array"""
    
    array[6]=11
    return array
def main():
    #zeros function will generate the array of zeros
    array=np.zeros(10)
    
    result=replace_vector(array)
    print(result)
if __name__=="__main__":
    main()

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).<br>


In [5]:
def reversed_array(array):
    """"
    Description:
        This function will reverse the array
    
    parameters:
        array:ndarray the data
        
    
    Returns:
        array:ndarray"""
    return np.flip(array)
def main():
    original_list=np.array([12, 13 ,14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 ,35 ,36, 37])
    new_list=reversed_array(original_list)
    print(f"original list : {original_list}")
    print(f"reversed list : {new_list}")
if __name__=="__main__":
    main()

original list : [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reversed list : [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.<br>

In [6]:
def create_matrix(matrix):
    """
    Description:
        This function will replace the 1 on the border and 0 on the inside
    
    Parameters:
        matrix:ndarray the data
    
    Returns:
        new_matrix: array"""
    
    new_matrix=matrix.reshape(5,5)

    new_matrix[0,:]=1
    new_matrix[-1,:]=1
    new_matrix[:,0]=1
    new_matrix[:,-1]=1
    return new_matrix
def main():
    matrix=np.zeros(25)
    result=create_matrix(matrix)
    print(result)
if __name__=="__main__":
    main()

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.<br>

In [7]:
def create_matrix(array):
    """
    Description:
        This function will add extra 2 rows and 2 columns with zeros and replace the center part with array
    
    Parameters:
        array:ndarray The data
    
    Returns:
        new_array:ndarray"""
    rows,colums=array.shape
    new_array=np.zeros((rows+2,colums+2),dtype=int)
    new_array[1:-1,1:-1]=array
    return new_array
    
def main():
    array=np.array([[1,1,1],[1,1,1],[1,1,1]],dtype=float)
    print(f"Original array:\n {array}")
    result=create_matrix(array)
    print(f"new array :\n {result}")
if __name__=="__main__":
    main()

Original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
new array :
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.<br>


In [8]:
def create_checkboard(rows,columns):
    """
    Description:
        This function will create a 8x8 matrix and print the 0`s and 1`s alternatively
    
    Parameters:
        rows: int number of rows in a matrix
        colums:int number of columns in a matrix 
    returns:
        checkboard:ndarray"""
    
    checkboard=np.zeros((rows,columns),dtype=int)
    checkboard[0::2,1::2]=1
    checkboard[1::2,::2]=1
    return checkboard
    
def main():
    rows=8
    columns=8

    result=create_checkboard(rows,columns)
    print(result)
if __name__=="__main__":
    main()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.<br>


In [9]:
def convert_list_tuple(list_elements,tuple_elements):
    """
    Description:
        This function is used to convert list and tuple to array
     
    Parameters:
        list_elements: list The data
        tuple_elements: tuple the data
    
    Returns:
        list_array: ndarray after converting to numpy array
        tuple_array: ndarray after convertunf to numpy array
     """
    list_array=np.array(list_elements)
    tuple_array=np.array(tuple_elements)
    return  list_array,tuple_array

def main():
    list_elements = [1, 2, 3, 4, 5,6]
    tuple_elements=(7,8,9,1,2,3)
    result,result1=convert_list_tuple(list_elements,tuple_elements)
    print(f"tuple to array: \n { result1.reshape(2,3)}")
    print(f"list to array: \n { result.reshape(2,3)}")
if __name__=="__main__":
    main()

tuple to array: 
 [[7 8 9]
 [1 2 3]]
list to array: 
 [[1 2 3]
 [4 5 6]]


9. Write a Python program to append values to the end of an array.<br>


In [10]:
def append_elements(array):
    """"
    Description:
        This function will append the two lists
    
    parameter:
        array:ndarray The original array
    
    returns:
        add_elements:ndarray the new array after appending"""
    
    add_elements=[int(number) for number in input("Enter the number to add to a array :").split(",")]
    add_elements=np.append(array,add_elements)
    return add_elements
def main():
    array=np.array([1,2,3])
    print(f"Original array: {array}")
    result=append_elements(array)
    print(f"new array:{result}")
if __name__=="__main__":
    main()


Original array: [1 2 3]
new array:[1 2 3 5]


10. Write a Python program to find the real and imaginary parts of an array of complex<br>
numbers.<br>

In [11]:


def get_real_imaginary_parts(array):
    """
    Description:
        This function is to find real and imaginary part
    
    parameters:
        array:ndarray given input
    return:
        real_part:real part of the array
        ima_part:imaginary part of the array

    """
  
    real_part = np.real(array)
    
    imaginary_part = np.imag(array)
    
    return real_part, imaginary_part

def main():
    array = np.array([1.00000000+0.j ,0.70710678+0.70710678j])
    real_part, imaginary_part = get_real_imaginary_parts(array)
    print(f"Real part: {real_part}")
    print(f"Imaginary part:{ imaginary_part}")
if __name__=="__main__":
    main()

Real part: [1.         0.70710678]
Imaginary part:[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.


In [12]:
def array_info(array):
    """
    Description:
        This function is used to find the size ,itemsize and bytes
    
    parameters:
        array:ndarray the given array
    
    returns:
        num_elemenst:int The numbers of elements present in the array
        element_size: int The size of the array
        total_bytes: int The total bytes of the array
    """
    num_elements = array.size
    element_size = array.itemsize
    total_bytes = array.nbytes
    return num_elements, element_size, total_bytes

def main():
    array = np.array([1,2,3])

    num_elements, element_size, total_bytes = array_info(array)
    print(f"Number of elements: {num_elements}")
    print(f"Length of one element in bytes:{ element_size}")
    print(f"Total bytes consumed by the elements:{ total_bytes}")
  
if __name__=="__main__":
    main()

Number of elements: 3
Length of one element in bytes:8
Total bytes consumed by the elements:24


12. Write a Python program to find common values between two arrays

In [13]:
def find_common(array1,array2):
    """
    Description:
        This function will print the common elements from the both the array
    
    parameters:
        array1:ndarray the array1 elements
        array2:ndarray the array2 elements
    
    returns:
        None"""
    result=np.array([],dtype=int)
    for i in array1:
        
        if i in array2:
           
            result=np.append(result,i)
    return result
def main():
    array1=np.array([0,10,20,40,60])
    array2=np.array([10,30,40])
    result=find_common(array1,array2)
    print(result)
if __name__=="__main__":
    main()

[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.


In [14]:
def set_difference(array1,array2):
    """
    Description:
        This function is used find the elements which are present only in the array1
    
    parameters:
        array1:ndarray the elements of the array1
        array2:ndarray the elements of the array2
    
    returns:
        result:ndarray"""
    result=np.array([],dtype=int)
    for i in array1:
        if i not in array2:
            result=np.append(result,i)
    return result

def main():
    array1=np.array([0,10,20,40,60,80])
    array2=np.array([10,30,40,50,70,90])
    result=set_difference(array1,array2)
    print(result)
if __name__=="__main__":
    main()

[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input array

In [15]:
def set_difference(array1,array2):
    """
    Description:
        This function is used find the elements which are present only in the array1 and array2
    
    parameters:
        array1:ndarray the elements of the array1
        array2:ndarray the elements of the array2
    
    returns:
        sorted array """
    result=np.array([],dtype=int)
    for i in array1:
        if i not in array2:
            result=np.append(result,i)
    for i in array2:
        if i not in array1:
            result=np.append(result,i)
    return np.sort(result)
def main():
    array1=np.array([0,10,20,40,60,80])
    array2=np.array([10,30,40,50,70,90])
    result=set_difference(array1,array2)
    print(result)
if __name__=="__main__":
    main()

[ 0 20 30 50 60 70 80 90]


15. Write a Python program compare two arrays using numpy.


In [16]:

def compare(array1, array2):
    """
    Description:
        Compares two numpy arrays and returns a dictionary with the results of various comparisons.
    
    Parameters:
        array1: numpy array, first array to compare.
        array2: numpy array, second array to compare.
    
    Returns:
        dict: A dictionary with comparison results for greater than, greater than or equal to,
            less than, and less than or equal to.
    """
    return {
        "Greater than": array1 > array2,
        "Greater than or equal to": array1 >= array2,
        "Less than": array1 < array2,
        "Less than or equal to": array1 <= array2
    }

def main():
    array1 = np.array([1, 5])
    array2 = np.array([4, 2])
    
    comparison_results = compare(array1, array2)
    
    for key, value in comparison_results.items():
        print(f"{key}: {value}")

if __name__ == "__main__":
    main()


Greater than: [False  True]
Greater than or equal to: [False  True]
Less than: [ True False]
Less than or equal to: [ True False]


16. Write a Python program to save a NumPy array to a text file.


In [17]:
def save_to_text(filename,array):
    """
    Description:
        This function will save the array into the new file 
    
    parameters:
        filename: The file name in which the data has to be saved
        array:ndarray the elements which has to be stored in the file
    return:
        None
    """
    np.savetxt(filename,array,fmt="%d",header="Array Elements")
def main():
    array=np.array([1,2,3],dtype=int)
    save_to_text('Array.txt',array)
if __name__=="__main__":
    main()

17.Write a Python program to create a contiguous flattened array.


In [18]:
def create_flattened_array(array):
    """
    Description:
        This function will convert multi dimension or 2 dimension into one dimension 
    
    parameters:
        array:ndarray the elements 
    
    returns:
        result:ndarray the one dimensional array
    """
    result=np.ravel(array)
    return result

def main():
    array=np.array([[10,20,30],[40,50,60]])
    print(f"The original array:\n{array}")
    result=create_flattened_array(array)
    print(f"The New flattened array:{result}")
if __name__=="__main__":
    main()

The original array:
[[10 20 30]
 [40 50 60]]
The New flattened array:[10 20 30 40 50 60]


18.Write a Python program to change the data type of an array.


In [19]:
def change_datatype(array):
    """
    Description:
        This function is used to change the datatype into float
    
    parameters:
        array:ndarray
    
    Returns:
        result: ndarray """
    result=np.array(array,dtype=float)
    return result

def main():
    array=np.array([[2,4,6],[6,8,10]],dtype=int)
    print(f"The original array which is int:\n {array}")
    result=change_datatype(array)
    print(f"The New array after changing the datatype to float :\n{result}")
if __name__=="__main__":
    main()


The original array which is int:
 [[ 2  4  6]
 [ 6  8 10]]
The New array after changing the datatype to float :
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


19. Write a Python program to create a 3-D array with ones on a diagonal and zeros

In [20]:
def diagonal_ones(array):
    """
    Description:
        This function will display all the diagonal elements as one
    
    parameters:
        array:ndarray the  input
    returns:
        array:ndarray The diagonal elements are 1"""
    j=0
    for  i in range(len(array)):
        array[j][j]=1
        j+=1
    return array

def main():

    array=np.zeros((3,3),dtype=int)
    result=diagonal_ones(array)
    print(result)

if __name__=="__main__":
    main()


[[1 0 0]
 [0 1 0]
 [0 0 1]]


20. Write a Python program to create an array which looks like below array.

In [21]:
def array_ones(array):
    """
    Description:
        This function will make one for each increasing the colums
    
    parameters:
        array:ndarray the  input
    
    returns:
        array :ndarray """
   
    for  i in range(len(array)):
        array[i,:i]=1
        
    return array

def main():

    array=np.zeros((4,3))
    result=array_ones(array)
    print(result)


if __name__=="__main__":
    main()


[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


21. Write a Python program to concatenate two 2-dimensional arrays

In [22]:
def add_arrays(array1,array2):
    """
    Description:
        This function is to concatenate the two arrays
    
    parameters:
        array1:ndarray The array1 elements
        array2:ndarrya The array2 elements
    
    returns:
        array:ndarray The concatenated array
    
    """
    #print(np.concatenate((array1,array2),axis=1))
    return np.hstack((array1,array2))
    
def main():
   
    array1=np.array([[0,1,3,],[5,7,9]])
    array2=np.array([[0,2,4],[6,8,10]])
    result=add_arrays(array1,array2)
    print(result)

if __name__=="__main__":
    main()

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


22. Write a Python program to make an array immutable (read-only)

In [23]:
def array_immutuable(array):
    """
    Description:
        This function is setting the numpy to immutuable
    
    parameters:
        array:ndarray This elements
    
    Returns:
        array:ndarray the array after setting to immutuable """
    array.flags.writeable=False
    return array
def main():
    array=np.array([1,2,3])
    result=array_immutuable(array)
    print(result)
    array[1]=1
if __name__=="__main__":
    main()

[1 2 3]


ValueError: assignment destination is read-only

23. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array

In [ ]:
def create_array(original_array):
    """
    Description:
        This function is used to create new array and multiplied by 3
    parameters:
        original_array: ndarray the data
    Returns:
        new_array:ndarray"""
    
    new_array=original_array*3
    return new_array
def main():
    
    original_array=np.arange(0,12)
    original_array=original_array.reshape(4,3)
    print(f"The original array: \n{original_array}")
    result=create_array(original_array)
    print(f"The new_array:\n {result}")
    

if __name__=="__main__":
    main()

The original array: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The new_array:
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]
 [27 30 33]]


24.Write a Python program to convert a NumPy array into Python list structure.


In [ ]:
def convert_array_list(array):
    """
    Description:
        This function is used to convert array to list
    
    parameters:
        array: ndarray its consisting of elements
    
    returns:
        list"""
    result=array.tolist()
    return result

def main():
    array=np.array([[0,1],[2,3],[4,5],[6,7]])
    result=convert_array_list(array)
    print(result)

if __name__=="__main__":
    main()

[[0, 1], [2, 3], [4, 5], [6, 7]]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array

In [ ]:
def format_array():
    """
    Description:
        This function formats an array by suppressing scientific notation and limiting the precision to 3 decimal places.
    
    Parameters:
        None
    
    Returns:
        numpy array: A numpy array with formatted values.
    """
    array = [1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01]
    formatted_array = ['{:.3f}'.format(x) for x in array]
    return np.array(formatted_array, dtype=float)

def main():
    formatted_array = format_array()
    print(formatted_array)

if __name__ == "__main__":
    main()


[0.00e+00 1.60e+00 1.20e+03 2.35e-01]


26. Write a Python program to how to add an extra column to an numpy array.


In [ ]:
def add_colum(array,column_array):
    """
    Description:
        This function is add a extra column in a existing one
    parameters:
        array:ndarray The input
        column_array:ndarray The column elements should be added  
    return:
        ndarray:"""
    result=np.column_stack((array,column_array))
    return  result

def main():
    array=np.array([[1,2,3],[4,5,6],[7,8,9]])
    new_column=np.array([7,8,1])
    result=add_colum(array,new_column)
    print(result)

if __name__=="__main__":
    main()

[[1 2 3 7]
 [4 5 6 8]
 [7 8 9 1]]


27. Write a Python program to remove specific elements in a numpy array.

In [ ]:
def remove_elements(array):
    """
    Description:
        This function is remove the elemenths based on the index
    
    parameters:
        array:ndarray the input
    
    returns:
        ndarray"""
    delete_index=[0,3,4]
    new_result=np.delete(array,delete_index)
    return new_result
def main():
    array=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
    result=remove_elements(array)
    print(result)
if __name__=="__main__":
    main()


[ 20  30  60  70  80  90 100]
